name: Build Axiom OS (Master)
on: 
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        run: sudo apt-get update && sudo apt-get install -y debootstrap squashfs-tools xorriso mtools gpg
      - name: Build
        run: |
          chmod +x scripts/build_axiom.sh
          ./scripts/build_axiom.sh
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: AxiomOS-Final
          path: output/AxiomOS.iso
